#!/usr/bin/env bash

shopt -s extglob

BUILDERDIR="$(dirname "$0")"

# variables needed later.
start_dir=`pwd`
nginx_install_dir="$HOME/nginx"
stage_dir="$start_dir/tmp"
nginx_stage_dir="$stage_dir/stage"
nginx_download_url="http://nginx.org/download/nginx-1.0.12.tar.gz"  #TODO configurable?


# functions
msg() {
    echo -e "\033[1;32m-->\033[0m $0:" $*
}

die() {
    msg $*
    exit 1
}

move_to_approot() {
    [ -n "$SERVICE_APPROOT" ] && cd $SERVICE_APPROOT
}

clean_nginx() {
    if [ -d $nginx_install_dir ] ; then
        msg "cleaning up ($nginx_install_dir)"
        rm -rf $nginx_install_dir
    fi
}

install_nginx() {
    local nginx_url=$nginx_download_url

    msg "installing Nginx into: $nginx_install_dir"

    # install nginx
    if [ ! -d $nginx_install_dir ] ; then
        msg "making directory: $nginx_install_dir "
        mkdir -p $nginx_install_dir
        
        msg "making directory: $nginx_stage_dir "
        mkdir -p $nginx_stage_dir

        msg "downloading nginx from ($nginx_url) and untaring into ($nginx_stage_dir) "
        wget -O - $nginx_url | tar -C $nginx_stage_dir --strip-components=1 -zxf -
        [ $? -eq 0 ] || die "can't fetch nginx"

        msg "Successfully download and untarred nginx"
        
        msg "move into $nginx_stage_dir "
        cd $nginx_stage_dir 

        msg "trying to compile nginx, and then install it"
        export CFLAGS="-O3 -pipe"
           ./configure   \
            --prefix=$nginx_install_dir \
            --with-http_addition_module \
            --with-http_dav_module \
            --with-http_geoip_module \
            --with-http_gzip_static_module \
            --with-http_realip_module \
            --with-http_stub_status_module \
            --with-http_ssl_module \
            --with-http_sub_module \
            --with-http_xslt_module && make && make install
        [ $? -eq 0 ] || die "Nginx install failed"

        msg "Successfully compiled and installed nginx"

        msg "remove some of the default config files from the nginx config directory that aren't needed"
        rm $nginx_install_dir/conf/*.default

        msg "cleaning up ($stage_dir) since it is no longer needed."
        rm -rf $stage_dir

        msg "change directories back to $start_dir"
        cd $start_dir

        msg "finished installing nginx."
    else
        msg "Nginx already installed, skipping this step."
    fi
}

build_profile(){
    cat > $start_dir/profile << EOF
export PATH="$nginx_install_dir/sbin:$PATH"
EOF

}

install_application() {

    msg "change directories to $start_dir"
    cd $start_dir

    msg "moving $start_dir/profile to ~/"
    mv $start_dir/profile ~/

    # Use ~/code and ~/current like the regular python service for better compatibility
    msg "installing application to ~/current/ from $start_dir"
    rsync -avH --delete --exclude "data" --exclude "README.rst" * ~/current/
}

# lets get started.

msg "Step 0: getting ready for build::"
move_to_approot

# If you want to rebuild nginx from scratch and remove a previously good compile
# uncomment this. Don't do this everytime, or else each build will be slow.
# msg "Step 1A: cleaup old nginx build::"
# clean_nginx

msg "Step 1: install nginx::"
install_nginx

msg "Step 2: build profile::"
build_profile

msg "Step 3: install application::"
install_application

msg "All done..."